# Generated by Django 2.2.6 on 2019-10-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apom', '0002_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
